from collection.map.HashRing import HashRing

hr = HashRing(5)
hr.addNode(12)
hr.addNode(18)
hr.addResource(24)
hr.addResource(21)
hr.addResource(16)
hr.addResource(23)
hr.addResource(2)
hr.addResource(29)
hr.addResource(28)
hr.addResource(7)
hr.addResource(10)
hr.printHashRing()
hr.addNode(5)
hr.addNode(27)
hr.addNode(30)
hr.printHashRing()
hr.removeNode(12)
hr.printHashRing()